#!/bin/bash

## 在/etc/udev/rules.d/下自动生成70-persistent-net.rules文件

RULES='/etc/udev/rules.d/70-persistent-net.rules'
TEMP='SUBSYSTEM=="net", ACTION=="add", DRIVERS=="?*", ATTR{address}=="xxxx",  KERNEL=="eth*", NAME="ethx"'
BONDING=`lsmod | grep -i bonding`

if [ -f $RULES ]; then
   read -p "File [ $RULES ] Exsits, Override ? " userInput 
   if [ X"$userInput" != Xy ]; then
     exit 1
   else
      mv $RULES $RULES.`date +%Y%m%d-%H%M%S`
      echo "# This file was regenerated by $0 " > $RULES
   fi   
fi

for ETH in `ip link show|egrep eth[0-9]|awk -F: '{print $2}'`
do
  
  if [ -f /sbin/ethtool ];  then
    MAC=`ethtool -P $ETH|awk '{print $3}'`
  elif [ -z "$BONDING" ];  then
    MAC=`ip link show $ETH |grep 'link/ether'|awk '{print $2}'`
  else
    echo "ERROR: ethtool NOT installed with bongding mode NICs ..."
    exit 2
  fi
  echo "$TEMP" | sed 's/xxxx/'$MAC'/;s/ethx/'$ETH'/' >> $RULES

done

echo
echo "creating UDEV file in $RULES ..."
echo '>>>'
cat $RULES
echo '<<<'
exit 0
